# Generated by Django 4.2.6 on 2023-10-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=30, verbose_name='Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo', models.TextField(null=True, verbose_name='Correo')),
                ('contrasena', models.CharField(max_length=256, null=True, verbose_name='Contraseña')),
                ('rol', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='libreria.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Libro_usuario',
            fields=[
                ('id_libro_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30, verbose_name='Estado')),
                ('id_libro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='libreria.libro')),
                ('id_usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='libreria.usuario')),
            ],
        ),
    ]
