# Generated by Django 4.2.6 on 2023-11-08 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libreria', '0002_rol_usuario_libro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.CharField(max_length=30, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='libro_usuario',
            name='id_usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.TextField(null=True, unique=True, verbose_name='Correo'),
        ),
    ]
